enable_testing()
function(unit_test name)
    add_executable(test_${name} tests/test_${name}.cpp)
    add_test(test_${name}_run test_${name})
    target_link_libraries(test_${name} parsing thread_parser)
    target_compile_definitions(test_${name} PRIVATE TEST)
endfunction()

unit_test(parser)
unit_test(r)
unit_test(ri)
unit_test(cop)
unit_test(i)
unit_test(j)
unit_test(block)
